### ISSUE TITLE
useQueryClient$ import

### ISSUE THREAD

**Issue by aboire** [XantreDev/preact-signals#104]
I cannot import useQueryClient$

@preact-signals/query version 2.0

**Comment by XantreDev** [comment]
Will check it

**Comment by aboire** [comment]
Thank you very much, I have useQueryClient$ now,
because setQueryData() is not present,
I would like to use it to modify data that comes from useInfiniteQuery$() after an action (example follow)

**Comment by XantreDev** [comment]
You're welcome
