### ISSUE TITLE
setQueryData is not a function

### ISSUE THREAD

**Issue by aboire** [XantreDev/preact-signals#111]
I can't apply a change to a `useInfiniteQuery$`

https://tanstack.com/query/latest/docs/framework/react/guides/infinite-queries#manually-removing-a-single-value-from-an-individual-page

```
const queryClient = useQueryClient$();
const newPagesArray =
   oldPagesArray?.pages.map((page) =>
     page.filter((val) => val.id !== updatedId),
   ) ?? []

queryClient.setQueryData(['projects'], (data) => ({
   pages: newPagesArray,
   pageParams: data.pageParams,
}))
```

`setQueryData is not a function`

and if I use
```
const queryClient = useQueryClient();
const newPagesArray =
   oldPagesArray?.pages.map((page) =>
     page.filter((val) => val.id !== updatedId),
   ) ?? []

queryClient.setQueryData(['projects'], (data) => ({
   pages: newPagesArray,
   pageParams: data.pageParams,
}))

```
I don't have any errors but it doesn't update

I don't know how you use it to delete in a useInfiniteQuery$?

**Comment by XantreDev** [comment]
We have a test for this case. I should work. I will investigate this issue
https://github.com/XantreDev/preact-signals/blob/a545b6bee1d14da60db578ee2ee220aed90ff7d7/packages/query/src/__tests__/standart-query/useInfiniteQuery.test.tsx#L1214-L1218

**Comment by XantreDev** [comment]
https://stackblitz.com/edit/vitejs-vite-6yh3uv?file=src%2FApp.tsx
