### ISSUE TITLE
Question: Passing signal to enabled

### ISSUE THREAD

**Issue by Munawwar** [XantreDev/preact-signals#181]
Hi, first off nice project! 🚀

Question: Shouldn't `enabled` take the signal and not `signal.value` in the readme example?

```js
const query = useQuery$(() => ({
  queryKey: ["user"],
  queryFn: () => fetchUser(),
  enabled: isUserRegistered.value, // <-- this part
}));
```

**Comment by XantreDev** [comment]
`useQuery$` takes callback as an argument - so it will subscribe to any signal reads inside of the callback

**Comment by Munawwar** [comment]
Right! I get it now.
