### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by victor-gapeev** [XantreDev/preact-signals#194]
Hi, i got next bug with last @preact-signals/query version: 

![screenshot1](https://github.com/user-attachments/assets/b43d609b-a560-44e2-8f85-331cadb344a6)

My custom hook to wrap Read entity queries:

```typescript
export default function useREntity<E, Q>(prefix: EntityList, query: Partial<Q> = {}) {
	const router = useLocation()
	const { logout } = useUser()

	const path = `/${prefix}`

	const q = useQuery$(() => ({
		queryFn: async ({ signal }) => {
			if (!signal?.aborted) {
				const response = await getRequest<E, Q>(path, query, signal)
				return response
			}
		},
		queryKey: [prefix, ...Object.values(query).map((q) => q + "")],
	}))

	if (q.data && !q.data.result) {
		if (q.data.code == 401) {
			logout()
			router.route("/login")
		}
	}

	return q
}
```

Error in preact code:
![image](https://github.com/user-attachments/assets/dd1b1214-191f-46d6-a37c-dd1ab7509252)

I also use the preact-iso package to create spa routing.

Update: 
This bug happens only after the first load, if I switch pages and return back, I can use filters and other parts, and everything works fine.

**Comment by XantreDev** [comment]
It's a strange behavior. I will investigate it

**Comment by victor-gapeev** [comment]
I`m sorry, it`s my fault. Above in my code I accidentally store useSignal result in global variables, which leads to strange bugs like this.
