### ISSUE TITLE
Computed signals rendered as variable in DOM get wrong typing

### ISSUE THREAD

**Issue by Mikescops** [XantreDev/preact-signals#216]
Hello,

Here is the code i'm trying to make working

```ts
import { computed, signal } from "@preact-signals/safe-react";

const apiResponse = signal({ data: null });
const apiResponseData = computed(() => JSON.stringify(apiResponse.value.data));

function App() {
    useEffect(() => {
        // make api call to localhost:3000/
        fetch("http://0.0.0.0:3000/")
            .then((response) => response.json())
            .then((data) => {
                apiResponse.value = { ...apiResponse.value, data };
            });
    });

    return (
                <p>{apiResponseData}</p>
     )
}

export default App;
```

Here is the typing error I'm getting on `{apiResponseData}`.

```
Type 'ReadonlySignal<string>' is not assignable to type 'ReactNode'
```

This issue was fixed in the recent versions of preact-signals already.
For now I can use this workaround but that's not ideal.

```
<p>{apiResponseData as unknown as ReactNode}</p>
```

Thanks!

**Comment by XantreDev** [comment]
Hey. Which version of `@preact-signals/safe-react` do you use?

**Comment by Mikescops** [comment]
Hi, I'm on `"@preact-signals/safe-react": "^0.8.0",`

This issue was fixed in the very last update of preact-signals, see changelog https://github.com/preactjs/signals/releases/tag/%40preact%2Fsignals-react%402.2.0

**Comment by XantreDev** [comment]
Yeah. Thank you for the help. I though `safe-react` do use the same types as `@preact/signals-react`, but I've mistaken it with `unified-signals`
It should be fixed in a next version

**Comment by XantreDev** [comment]
https://github.com/XantreDev/preact-signals/releases/tag/%40preact-signals%2Fsafe-react%400.8.1

**Comment by Mikescops** [comment]
Thanks a lot!

**Comment by Mikescops** [comment]
Confirmed this works as expected!
