### ISSUE TITLE
Capturing of component variable in effects/computeds

### ISSUE THREAD

**Issue by XantreDev** [XantreDev/preact-signals#89]
React by design is focused on dependency arrays, it's bad for performance, but when dealing with signals it can be useful for interacting with traditional state.
We can adopt pattern from reanimated, where all variables inside of `useDerivedValue` closure is extracted to fill deps array automatically. It will give us simplicity of no deps array, but with possibility to recalculate signals/effect depending on closure. It will be major shift for simplicity

**Comment by XantreGodlike** [comment]
Reanimated collects all vars inside of worklet to the [clojure](https://github.com/software-mansion/react-native-reanimated/blob/1ea5d1d3b92637d52236bf6bc8ceca0898bb14fc/src/reanimated2/hook/useDerivedValue.ts#L30C3-L30C55). It uses this value as useEffect dependency

**Comment by XantreGodlike** [comment]
In this case we will have more reexecutions that we actually want. But we can wrap closure values with signals to track executions reactively
API
Input:
```tsx
const a = 10
const c = Math.random()
useComputed$(() => {
	return a + c
})
```
Output:
```tsx
const a = 10
const c = Math.random()
useComputed$((clojure) => {
	return clojure.a.value + clojure.b.value
}, {a, b})
```

**Comment by XantreGodlike** [comment]
I like the third api. I want to specify it more: 
Two variants of state `$state`, `$bindedState`
`$state` is editable
```ts
let text= $state(0)

const onClick = () => {
  text += 10
}
```

**Comment by XantreGodlike** [comment]
I've made a decision to rename $bindedState -> `$useLinkedState`, `$state` -> `$useState` and also add `$state` as wrapper around signals
