### ISSUE TITLE
doesnt work on nextjs 14.2 with turbopack

### ISSUE THREAD

**Issue by hiddenLadder** [XantreDev/preact-signals#97]
![image](https://github.com/XantreDev/preact-signals/assets/89526742/d4eae112-aca3-498f-9500-c85ff31f7ace)

**Comment by XantreDev** [comment]
Probably I need to update swc version

**Comment by XantreDev** [comment]
Reproduced. https://swc.rs/docs/plugin/selecting-swc-corefor is not valid url btw

**Comment by XantreDev** [comment]
I see: Next team bumped swc version to 0.90 in `14.2.0` version of Next.js. swc bump will need to make some rewrite, but i will try to release it soon
As workaround you can use next `~14.1.0`
